Update CladeTime tree_as_of and sequence_as_of date handling
reichlab/cladetime pull request #34
Opened 2024-10-09 20:50 UTC by bsweger

Resolve #33 

See the linked issue for details. Essentially, this PR modifies two cases when setting `sequence_as_of` and `tree_as_of` dates for `CladeTime` objects:

* if no tree_as_of parameter is specified when instantiating CladeTime, tree_as_of should default to the sequence_as_of value.

* if either tree_as_of or sequence_as_of is a future date, CladeTime instantiation should give a warning and use the current datetime value instead.

2024-10-09 20:53 UTC, bsweger commented on src/cladetime/cladetime.py
> +    def sequence_as_of(self, date) -> None:
The logic for setting `sequence_as_of` and `tree_as_of` default values is no longer the same, so created a setter for each of these properties.

2024-10-10 17:29 UTC, elray1 requested changes
1 minor change suggested.

2024-10-10 17:29 UTC, elray1 commented on src/cladetime/cladetime.py
> +            sequence_as_of = datetime.now()
Could/should we get rid of this as it's covered in `self._validate_as_of_date`?
```suggestion
```

2024-10-10 17:51 UTC, elray1 commented on src/cladetime/cladetime.py
> +        utc_now = datetime.now().replace(tzinfo=timezone.utc)
might this actually end up pointing to a past time?

```
>>> now = datetime.now()
>>> utc_now = now.replace(tzinfo=timezone.utc)
>>> # Create a timezone object for Eastern Time (UTC-4)
>>> eastern_tz = timezone(timedelta(hours=-4))
>>> eastern_now = now.replace(tzinfo=eastern_tz)
>>> 
>>> now
datetime.datetime(2024, 10, 10, 13, 50, 2, 440530)
>>> utc_now
datetime.datetime(2024, 10, 10, 13, 50, 2, 440530, tzinfo=datetime.timezone.utc)
>>> eastern_now
datetime.datetime(2024, 10, 10, 13, 50, 2, 440530, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=72000)))
>>> 
>>> eastern_now > utc_now
True
```

It seems like `replace` here does not calculate the time corresponding to "now" in UTC...

2024-10-10 17:53 UTC, elray1 commented on src/cladetime/cladetime.py
> +        utc_now = datetime.now().replace(tzinfo=timezone.utc)
Maybe the operation we want is
```
utc_now = datetime.now(tz=timezone.utc)
```

2024-10-10 17:55 UTC, elray1 commented on src/cladetime/cladetime.py
> +        utc_now = datetime.now().replace(tzinfo=timezone.utc)
flagging same discussion as above

2024-10-10 19:13 UTC, bsweger commented on pyproject.toml
> +    "ignore::cladetime.exceptions.CladeTimeFutureDateWarning",
It suppresses warning messages from pytest output (I find them unsightly). CladeTimeFutureDateWarning are tested using the `pytest.raises` construct to make sure they're raised when expected.

2024-10-10 20:00 UTC, elray1 approved these changes
this all looks good to me, thanks!

2024-10-10 20:08 UTC, merged